plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.7
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
